from dataclasses import dataclass
from enum import Enum

class PassiveSide(Enum):
    Left = ...
    Right = ...

class AggressiveSide(Enum):
    Top = ...
    Bottom = ...

class Direction(Enum):
    Up = ...
    UpRight = ...
    Right = ...
    DownRight = ...
    Down = ...
    DownLeft = ...
    Left = ...
    UpLeft = ...

class Win(Enum):
    OwnWin = ...
    OpponentWin = ...
    GameOngoing = ...

@dataclass
class Quarter:
    own: int
    enemy: int

@dataclass
class Board:
    top_left: Quarter
    top_right: Quarter
    bottom_left: Quarter
    bottom_right: Quarter

@dataclass
class Move:
    passive_source_index: int
    aggressive_source_index: int
    passive_side: PassiveSide
    aggressive_side: AggressiveSide
    direction: Direction
    times_moved: int

@dataclass
class State:
    board: Board
    move: Move
    win: Win

start_state: State = ...

def get_next_states(board: Board) -> [State]: ...
def reverse_board(board: Board) -> Board: ...
def to_bit_string(bitboard: int) -> str: ...
def print_board(board: Board) -> None: ...
def print_bitboard(bitboard: int) -> None: ...
def popcnt(b: int) -> int: ...